# TEMPLATE PER CHI HA GIA IL SENSORE PER MISURARE LA LUCE ESTERNA IN LUX
#
# NECESSARIO AVERE NEL FILE DI CONFIGURAZIONE questa riga: sensor: !include sensor.yaml
# 
# se abbiamo gia configurato dei sensori direttamente in configuration.yaml basterà inserire al di sotto di "sensor: "
# altrimenti se non abbiamo nessun sensore, aggiungere la riga "sensor: " e incollare il codice sotto.
#

- platform: template
  sensors:
    sunlight_opacity:
      value_template: >-
        {%- set lux = states('sensor.LUXOMETRO') | float %}
        {%- set min_lux = 0 %}
        {%- set max_lux = 1000 %}  # <--- QUESTO DIPENDE DALLA CALIBRAZIONE DEL SENSORE, SE IN UNA GIORNATA DI MOLTO 
        {%- if lux <= min_lux %}   #      SOLE MISURA AD ES 4000lx QUI SI METTERÀ 4000 AL POSTO DI 1000
          0
        {%- elif lux >= max_lux %}
          1
        {%- else %}
          {{ ((lux - min_lux) / (max_lux - min_lux)) | round(2) }}
        {%- endif %}
